/**
 * Tool argument types for restricted auth stubs (generated by api2ai — do not edit).
 * Matches InvokeOptions in the generated *-tools module.
 */
export type InvokeOptions = {
    /** MCP tool arguments only (not visible to the agent: host context via mcpHostAdapter). */
    pathParams?: Record<string, string | number | boolean>;
    query?: Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
    headers?: Record<string, string>;
    body?: unknown;
};

export type RestrictedHostContext = {
    credential: string;
    jwt?: Record<string, unknown>;
};
