import type { Model } from 'api-2-ai-dsl-language';
import { getAccessKind } from 'api-2-ai-dsl-language';
import {
    ensureCheckedAuthStubsFromSource,
    parameterCheckExportName,
    renderParameterCheckerImports,
    renderParameterCheckersMap,
    type AccessKind
} from '@core2ai/core/codegen';

export type ToolAccess = AccessKind;

export function listCheckedToolNames(model: Model): string[] {
    const names: string[] = [];
    for (const operation of model.operations) {
        if (getAccessKind(operation) === 'checked' && operation.toolName?.trim()) {
            names.push(operation.toolName.trim());
        }
    }
    return names;
}

export { parameterCheckExportName, renderParameterCheckerImports, renderParameterCheckersMap };

export const AUTH_INVOKE_OPTIONS_BASENAME = 'api2ai-invoke-options';

export function renderAuthInvokeOptionsTypeFile(): string {
    return `/**
 * Tool argument types for checked access auth stubs (generated by api2ai — do not edit).
 * Matches InvokeOptions in the generated *-tools module.
 */
export type InvokeOptions = {
    /** MCP tool arguments only (not visible to the agent: host context via mcpHostAdapter). */
    pathParams?: Record<string, string | number | boolean>;
    query?: Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
    headers?: Record<string, string>;
    body?: unknown;
};

export type CheckedHostContext = {
    credential: string;
    jwt?: Record<string, unknown>;
};
`;
}

export async function ensureCheckedAuthStubs(source: string, model: Model): Promise<Map<string, string>> {
    return ensureCheckedAuthStubsFromSource(
        source,
        listCheckedToolNames(model),
        AUTH_INVOKE_OPTIONS_BASENAME,
        renderAuthInvokeOptionsTypeFile()
    );
}

export function renderInvokeCredentialAndParameterCheck(
    hasAuth: boolean,
    hasChecked: boolean,
    typescript = false
): string {
    const credentialGuard = hasAuth
        ? `
    if (tool.access !== 'public') {
        if (!credential || !String(credential).trim()) {
            throw new Error(
                'Missing host credential. Pass --auth-env on mcp-serve.mjs and set the variable (re-read on every tool call).'
            );
        }
    }`
        : '';

    const checkedAccessBlock = hasChecked
        ? `
    if (tool.access === 'checked') {
        const check = parameterCheckers[toolName];
        if (typeof check !== 'function') {
            throw new Error('No parameter checker for checked tool: ' + toolName);
        }
        optionsResolved = await Promise.resolve(
            check(options, {
                credential: String(credential).trim(),
                jwt: host.jwt
            })
        );
    }`
        : '';

    const optionsResolvedDecl = hasChecked ? 'let optionsResolved = options' : 'const optionsResolved = options';

    return `${credentialGuard}
    ${optionsResolvedDecl};${checkedAccessBlock}
    const normalizedBaseUrl = baseUrl.endsWith('/') ? baseUrl.slice(0, -1) : baseUrl;
    const pathParams = { ...(optionsResolved.pathParams ?? {}) };
    let resolvedPath = tool.path;
    for (const [key, value] of Object.entries(pathParams)) {
        resolvedPath = resolvedPath.split('{' + key + '}').join(encodeURIComponent(String(value)));
    }

    const url = new URL(normalizedBaseUrl + resolvedPath);
    appendSerializedQueryParams(url.searchParams, tool.toolName, optionsResolved.query);
    const requestHeaders${typescript ? ': Record<string, string>' : ''} = {
        'content-type': 'application/json',
        ...(optionsResolved.headers ?? {})
    };`;
}
