import { type Module, inject } from 'langium';
import {
    createDefaultModule,
    createDefaultSharedModule,
    type DefaultSharedModuleContext,
    type LangiumServices,
    type LangiumSharedServices,
    type PartialLangiumServices
} from 'langium/lsp';
import { Api2AiDslGeneratedModule, Api2AiDslGeneratedSharedModule } from './generated/module.js';
import { Api2AiDslCompletionProvider } from './api-2-ai-dsl-completion-provider.js';
import { Api2AiDslValueConverter } from './api-2-ai-dsl-value-converter.js';
import { Api2AiDslValidator, registerValidationChecks } from './api-2-ai-dsl-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type Api2AiDslAddedServices = {
    validation: {
        Api2AiDslValidator: Api2AiDslValidator;
    };
};

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type Api2AiDslServices = LangiumServices & Api2AiDslAddedServices;

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const Api2AiDslModule: Module<Api2AiDslServices, PartialLangiumServices & Api2AiDslAddedServices> = {
    parser: {
        ValueConverter: () => new Api2AiDslValueConverter()
    },
    validation: {
        Api2AiDslValidator: () => new Api2AiDslValidator()
    },
    lsp: {
        CompletionProvider: (services) => new Api2AiDslCompletionProvider(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createApi2AiDslServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices;
    Api2AiDsl: Api2AiDslServices;
} {
    const shared = inject(createDefaultSharedModule(context), Api2AiDslGeneratedSharedModule);
    const Api2AiDsl = inject(createDefaultModule({ shared }), Api2AiDslGeneratedModule, Api2AiDslModule);
    shared.ServiceRegistry.register(Api2AiDsl);
    registerValidationChecks(Api2AiDsl);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Api2AiDsl };
}
